name: Commit and push changes

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags.

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Install Python 3.x version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run script
      run: python main.py
      env: # Set the secret as an input
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        changed=$(git diff --cached --exit-code)
        if [ -n "$changed" ]; then
          git commit -m "Auto update from GitHub Action"
          git push
        fi
